"""add alertTracker

Revision ID: 109111156046
Revises: 02433735a595
Create Date: 2021-12-23 16:29:32.369456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109111156046'
down_revision = '02433735a595'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_tracker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('stockID', sa.Integer(), nullable=True),
    sa.Column('priceAtUserInput', sa.Float(), nullable=True),
    sa.Column('priceDiff', sa.Float(), nullable=True),
    sa.Column('crossType', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stockID'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_tracker')
    # ### end Alembic commands ###
