"""update table

Revision ID: 514df39a2731
Revises: e49f49420a5e
Create Date: 2021-12-23 22:15:07.772748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514df39a2731'
down_revision = 'e49f49420a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_tracker', sa.Column('desiredPrice', sa.Float(), nullable=True))
    op.drop_column('alert_tracker', 'priceDiff')
    op.drop_column('alert_tracker', 'crossType')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_tracker', sa.Column('crossType', sa.BOOLEAN(), nullable=True))
    op.add_column('alert_tracker', sa.Column('priceDiff', sa.FLOAT(), nullable=True))
    op.drop_column('alert_tracker', 'desiredPrice')
    # ### end Alembic commands ###
