"""remove alert check time

Revision ID: 78349749b2b1
Revises: dcb936ae4715
Create Date: 2021-12-28 13:12:38.313736

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78349749b2b1'
down_revision = 'dcb936ae4715'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_tracker', 'lastCheckTime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_tracker', sa.Column('lastCheckTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
