"""user tokens

Revision ID: a11ff6ea26cd
Revises: 78349749b2b1
Create Date: 2021-12-28 18:40:35.298343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a11ff6ea26cd'
down_revision = '78349749b2b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('APItoken', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('APItoken_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_APItoken'), 'user', ['APItoken'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_APItoken'), table_name='user')
    op.drop_column('user', 'APItoken_expiration')
    op.drop_column('user', 'APItoken')
    # ### end Alembic commands ###
