"""add status

Revision ID: e49f49420a5e
Revises: 109111156046
Create Date: 2021-12-23 17:39:32.643418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49f49420a5e'
down_revision = '109111156046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_tracker', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_tracker', 'status')
    # ### end Alembic commands ###
