"""update alertracker

Revision ID: dcb936ae4715
Revises: 514df39a2731
Create Date: 2021-12-24 16:52:12.228410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb936ae4715'
down_revision = '514df39a2731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_tracker', sa.Column('lastCheckTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_tracker', 'lastCheckTime')
    # ### end Alembic commands ###
